### PR TITLE
Added importer for gamelist.xml

### PR DESCRIPTION
**Pull request by mgerhardy**
This allows me to use any scraper available that is able to export to gamelist.xml
and import this into the skyscraper db

I was trying different scrapers to see which one gave the best results. I ended up having a lot of images and videos downloaded already but still want them to be in the skyscraper db. This "scraper" allows me to import data from an existing gamelist.xml

It handles relative and absolute paths given in the xml file.

Maybe useful for others - maybe not.

### CODE REVIEW

**Comment by muldjord** [comment]
I like the idea, though I would like for this to somehow be part of the import scraping module that already exists, as not to bloat the list of scrapers. I'll give this some thought. My current importer requires one xml file per game, which is pretty silly actually. But I think I could add an "EmulationStation" mode to the current importer. I'll leave the pull request, I might use some of the code. Thanks.

**Comment by muldjord** [comment]
I think I've concluded that it makes sense to have this as a separate module. Could you rename it to "esgamelist" instead to better differentiate it from the import module? So the class would be "ESGamelist" and the module name would be "esgamelist". So it's basically a scraper for information contained in EmulationStation gamelists.

**Comment by mgerhardy** [comment]
will do tomorrow.  thanks a lot

**Comment by mgerhardy** [comment]
ok, rebased against `master` and renamed the class and options.

**Comment by muldjord** [comment]
Thanks for the contribution. I might fix some stuff in the code in the coming days, I haven't looked it over properly, just fixed some indentation and SS ifndef style and added header. :)

**Comment by muldjord** [comment]
I ended up rewriting most of it to be less error prone and conform to the Skyscraper design. Functionality is the same. Will be in 2.9.2.

**Comment by Enverex** [comment]
> basePath = QDir::homePath() + "/RetroPie/roms/" + config->platform + "/";

Just noticed this hard-coded into one of the paths. Is this scraper supposed to be RetroPie only?

**Comment by muldjord** [comment]
It is built with RetroPie in mind but works on pretty much any Linux distro. This exact file is the only thing that is hardcoded for RetroPie usage, but even here it also allows you to import from the ~/·skyscraper/import/gamelist.xml location. So no, it is by no means RetroPie only.

**Pull request merged**
