### PR TITLE
Improve install error handling

### LINKED ISSUE #208: Return error code when build fails
**Describe the bug**
When installing Skyscraper it can fail during compilation, but it returns the exit code 0. This makes it hard to use in a automated scenario as things will continue as if the installation succeeded.

**To Reproduce**
1. Use a very cheap computer.
2. `curl -L https://raw.githubusercontent.com/muldjord/skyscraper/master/update_skyscraper.sh | bash`

**Special circumstances**
Running in a VM in Azure. Trying to find the cheapest VM's and the top 3 cheapest makes this easy to reproduce. They all use the same Ubuntu 18.04 image but maybe have to limited memory or something.

**Terminal output**

Full log [here](https://pastebin.com/eaTHH68e).

```
--- Building Skyscraper v.3.4.6 ---
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.4.6\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o main.o src/main.cpp
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.4.6\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o skyscraper.o src/skyscraper.cpp
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.4.6\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o netcomm.o src/netcomm.cpp
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.4.6\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o xmlreader.o src/xmlreader.cpp
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make: *** [main.o] Error 4
make: *** Waiting for unfinished jobs....
Makefile:912: recipe for target 'main.o' failed
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make: *** [skyscraper.o] Error 4
Makefile:928: recipe for target 'skyscraper.o' failed
```

**Technical information**
 - Skyscraper version: 3.4.6
 - Internet connection: adsl, I think
 - OS: Ubuntu
 - OS Version 18.04

**Additional context**
I think the problem is here:
```
echo "--- Installing Skyscraper v.${LATEST} ---"
sudo make install
if [ $? != 0 ]
then
	rm VERSION
	exit
fi
```

`exit` without a parameter will use the exit code from the last command (according to [this](https://www.tldp.org/LDP/abs/html/exit-status.html)), which in this case is `rm VERSION` that ran successfully.
> The equivalent of a bare exit is exit $? or even just omitting the exit.

Perhaps something like this could work?
```
echo "--- Installing Skyscraper v.${LATEST} ---"
sudo make install
exitCode=$?
if [ $exitCode != 0 ]
then
	rm VERSION
	exit $exitCode
fi
```

### PR DESCRIPTION
**Pull request by seriema**
* Extract an error handling method to slim down the script and avoid repetition
* Conditionally call the error handler on error, avoids "if" statement with exit code
* Ignore "make clean" errors with --ignore-errors
* Ignore removal of nonexistent files ("rm .qmake.stash") with --force

Closes #208

---

I suspect it's the comparison with `=` that's meant for strings that wasn't working (`-ne` would be for comparing numbers). Using `||` means the right side is only called if the left failed, which is both safer and looks cleaner.

Log showing the error handling working (full log [here](https://pastebin.com/zN8KZai6)):
```
--- Building Skyscraper v.3.4.6 ---
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.4.6\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o main.o src/main.cpp
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.4.6\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o skyscraper.o src/skyscraper.cpp
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.4.6\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o netcomm.o src/netcomm.cpp
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.4.6\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o xmlreader.o src/xmlreader.cpp
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make: *** [main.o] Error 4
make: *** Waiting for unfinished jobs....
Makefile:912: recipe for target 'main.o' failed
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make: *** [skyscraper.o] Error 4
Makefile:928: recipe for target 'skyscraper.o' failed
--- Failed to build Skyscraper v.3.4.6, exiting with code 2 ---

Exited with code exit status 2
CircleCI received exit code 2
```

### CODE REVIEW

**Comment by muldjord** [comment]
I'm not sure why you got that error originally, the script has been working well for me on Ubuntu 18.04 and RetroPie ever since I wrote it. But regardless, I agree this is an improvement. I don't usually accept pull requests but I'll make an exception in this case. Thanks for the contribution.

**Comment by seriema** [comment]
@muldjord Thank you for accepting it!

There's some things I noticed while working on this that I might as well share:
1. `make -j` defaults to the maximum number of jobs so the number in `-jX` isn't needed.
    > If the ‘-j’ option is followed by an integer, this is the number of recipes to execute at once; this is called the number of job slots. If there is nothing looking like an integer after the ‘-j’ option, there is no limit on the number of job slots. The default number of job slots is one, which means serial execution (one thing at a time).
    > https://www.gnu.org/software/make/manual/make.html#Parallel
1. `rm VERSION` on line 14 is safe because the `VERSION` file is created when it doesn't exist (lines 5-9), but using `--force` could be useful so things don't error out during error handling.
1. `qmake || handle_error "clean old"` on line 29 was something I considered not doing any error handling on. I know too little about `qmake` so I kept it, but what's the errors that can happen? On a new install there's nothing to clean, so I expected it to fail and call `handle_error`. It didn't during my tests, but if I used `set -e` (abort on error) it would quit with error code 2. So there can be cases where the install doesn't happen because the cleaning fails but it didn't need to abort. Don't know if there should be some check for an old install before trying to remove it?

Anyway, as you said it's been working fine for a long time. But the error handling was never working, so now you might notice the errors that were always there. My project [seriema/retro-cloud](https://github.com/seriema/retro-cloud) is mainly setup scripts (and it uses Skyscraper) so I'd be happy to help if I can.

**Comment by muldjord** [comment]
> But the error handling was never working, so now you might notice the errors that were always there.

You are right, so this is a great improvement. But I don't believe that is connected to the initial error you saw: `g++: internal compiler error: Killed (program cc1plus)` I believe that is caused by the low-spec system and the previously hardcoded `-j4` which was a very recent addition I did.

1. I tried compiling with `-j` and, as you state, it seems to simply use as many as it can. Can you verify that this works on your low-spec VM? I am a bit worried about it, as some users seem to state that it can cause it to use more than the machine can provide. And the man page description is a bit obscure simply stating `If the  -j  option  is given without an argument, make will not limit the number of jobs that can run simultaneously`... That is a pretty vague description.

From https://stackoverflow.com/questions/52830504/whats-the-meaning-of-make-j-without-a-number

> @Jade Unlimited means It might fork more jobs than you have processor cores available.

EDIT: Here's some pretty worrying first-hand with `-j`
https://unix.stackexchange.com/questions/316644/is-make-j-with-no-argument-dangerous

I think I'll leave it as it is `-j$(nproc)`

2. I don't mind either way. I'll add it.

3. `qmake` will mainly fail if an extremely old version of Qt is present I believe. Probably down in Qt < 5 where the qmake script is not compatible. So it could happen, but it would be pretty niche cases.

I'm not sure about the `make clean` part. As long as `qmake` has been executed, it will have a `make clean` target. And as far as I know it shouldn't fail out on that. Or at least, if it does, it's benign. So it's fine as it is now in my opinion.

**Comment by seriema** [comment]
Oh absolutely, my issue came from `-j4` failing _silently_. As I need to be aware of _any_ failure I mainly focused on catching errors, whatever they may be.
_Edit: I don't need to run Skyscraper on a low-spec VM so _support_ for any other `j` than `j4` isn't necessary for me. As long as it error's out and doesn't end with exit code 0 I'm good._

1. Sure. I've queued one now. Will let you know when it's done.
1. 👍 
1. Good to know.

**Comment by seriema** [comment]
It took 2h 12m 😅 and it failed with a whole lot of:
(Full log [here](https://circleci.com/api/v1.1/project/github/seriema/retro-cloud/1048/output/102/0?file=true&allocation-id=5e91d859d34285443d751d2a-0-build%2F142E821))
```
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make: *** [mobygames.o] Error 4
Makefile:1108: recipe for target 'mobygames.o' failed
--- Failed to build Skyscraper v.3.4.6, exiting with code 2 ---

Exited with code exit status 2
```

I reacted to the `-l` flag by the way, but I'm not familiar with load values:
> When the system is heavily loaded, you will probably want to run fewer jobs than when it is lightly loaded. You can use the ‘-l’ option to tell make to limit the number of jobs to run at once, based on the load average. The ‘-l’ or ‘--max-load’ option is followed by a floating-point number. For example,
> `-l 2.5`
> will not let make start more than one job if the load average is above 2.5. The ‘-l’ option with no following number removes the load limit, if one was given with a previous ‘-l’ option.
> More precisely, when make goes to start up a job, and it already has at least one job running, it checks the current load average; if it is not lower than the limit given with ‘-l’, make waits until the load average goes below that limit, or until all the other jobs finish.
> https://www.gnu.org/software/make/manual/make.html#Parallel

I'd leave it at `-j$(nproc)` or `-j4`.

**Comment by muldjord** [comment]
> I'd leave it at -j$(nproc) or -j4.

Gotcha, gonna leave it at `-j$(nproc)`. Thanks for testing once again.

**Pull request merged**
