### PR TITLE
adding Neo Geo CD support

### PR DESCRIPTION
**Pull request by meveric**
nothing fancy, just adding a new platform

### CODE REVIEW

**Comment by muldjord** [comment]
Thanks, but please just request the platform in an issue, I will add it if I see fit to do so. It basically takes longer for me to review and verify this code than to add the platform myself. I appreciate the sentiment, but I am not looking for pull requests. Unfortunately I can't disable it on github.

**Comment by igno2k** [comment]
Hi,
is it possible to reopen this issue and add Neo Geo CD support?

**Comment by muldjord** [comment]
EDIT: I will add cd-rom extensions to the already existing `neogeo` platform. That should work. If you have arguments for adding it as a separate platform, please let me know. I'd like to refrain from adding it, as it is not an official RetroPie platform, and there's already a `neogeo` platform.

EDIT2: You can test this by adding
```
[neogeo]
addExtensions="*.cue *.chd *.iso"
```
to your [config.ini](https://github.com/muldjord/skyscraper/blob/master/docs/CONFIGINI.md) file. Let me know if that works.

**Comment by igno2k** [comment]
Thanks, I have already tried that of course :)

Problem is that screenscraper will not find Neo Geo CD when using the Neo Geo platform. Neo Geo CD is listed as a separate platform on screenscraper.

EDIT:
platform code on screenscraper is 70 for Neo Geo CD and 142 for Neo Geo

**Comment by muldjord** [comment]
Ah, yes, I see. It's not even a sub-platform of neo-geo on ScreenScraper. I wonder why they chose to do it like that. But that kind of settles it then. I can't fetch two different platforms at once, so I'll have to add it as a separate platform. I'll name it `neogeocd` which will also be where the roms must be placed. I'll make it recognize `*.iso *.cue *.chd`. Please let me know if more extensions are needed.

**Comment by igno2k** [comment]
Perfect - just tested it, works fine!
Thanks a lot for the fast update!

**Pull request closed without merging**
