### PR TITLE
added reference to updated fork

### PR DESCRIPTION
**Pull request by detain**
If your not accepting pull requests how about linking to my fork which ill keep updated.  I plan to keep it fully backwards compatible and mostly add additional platforms, update file-masks, keep mameMap updated, improve api usage.

### CODE REVIEW

**Comment by HVR88** [comment]
@detain Can you turn on the ability to post issues on your fork (to help with contributions)?

I'd like to request adding support for additional medias, primarily for ScreenScraper. Box back, manuals, support (cart).  I might be able to add this myself if I have some additional free time. It doesn't look very difficult to add to the screenscraper and cache source files at least to enable downloading.  I haven't looked yet at the generation code to see how the media are written to the ES gamelist or Pegasus metadata files. And lastly, any code necessary to control anything new in the ini and command-line args.

**Comment by HVR88** [comment]
Detain's fork: https://github.com/detain/skyscraper

**Comment by muldjord** [comment]
Added note about fork to readme.

**Comment by muldjord** [comment]
I still fix bugs when they are reported and I will update API's too when required. Skyscraper is where I personally want it to be. But I will keep an eye on your fork from time to time, and consider making the link more pronounced in case I feel like it remains active, stable and grows in a direction I agree with.

**Pull request closed without merging**
