### PR TITLE
Adding cover to gamelist.xml also as `thumbnail`

### PR DESCRIPTION
**Pull request by yisraeldov**
In the default theme, 'carbon' `thumbnail` is being used instead of cover.

Add an additional `thumbnail` entry to gamelist.xml that points to `cover`

### CODE REVIEW

**Comment by muldjord** [comment]
> In the default theme, 'carbon' thumbnail is being used instead of cover.

I have looked into `<thumbnail>` before. And as far as I know, this statement is simply incorrect. The theme uses `md_image` which can be either `<image>` or `<thumbnail>` from the gamelist.xml depending on the situation as described [here](https://github.com/RetroPie/EmulationStation/pull/362).

`<thumbnail>` is only used in grid-views (as described [here](https://github.com/RetroPie/EmulationStation/blob/master/GAMELISTS.md)) and as a stand-in for video if the video is delayed. And in those cases this would have no impact, as the `<image>` tag would already be used to provide this.

`<thumbnail>` is basically there to provide an image that loads faster, hence the name *thumbnail*. Simply copying the `<image>` tag into `<thumbnail>` seems like a copy / paste hack to me. I might provide a thumbnail in the future, but not like this.

**Comment by yisraeldov** [comment]
So actually your statement is "incorrect". `Thumbnail` is being used in all of the views that show a list of images, `image` is what is being used in place of video (the opposite of what you said).  

So I'm not copying `image` to `thumbnail`, rather `cover`.

From the document that you linked the `cover` is never being used by emulation station. `wheel` and `marquee` are also not mentioned. I know that `marquee` is being used in the `tile` layout. 

Take a look at the gif. where I use `cover` as `thumbnail` . You can see that the `thumbnail` is being used in almost every view, except for `tile`

I would suggest that for ES you should **replace** `cover` with `thumbnail` as it is not being used. 

es

**Comment by muldjord** [comment]
EDIT: Please don't spend any more time on this. I am researching it myself directly in the ES source code and documentation.

--------

Thanks, that was *a lot* more useful. I will look into this and provide the code myself.

For future reference, consider providing more than two lines of text as a description when you want to contribute to projects. I've now spend more than an hour on this myself after getting your PR which, frankly, was not how I wanted to spend my Sunday. All for two lines of code I could add myself in 10 seconds. Providing the documentation to begin with in a feature request rather than a PR would have been a lot more useful to me in this case. But for some reason people rarely feel the need to do the work involved in proper documentation. Unfortunately Github does not provide a way to disable or provide requirements for PR's.

**Comment by muldjord** [comment]
This has now been implemented. According to the ES source code the `<cover>` node is no longer supported. I've therefore decided to replace it with the `<thumbnail>` node as suggested. It is a bit of a hack since a cover is not a thumbnail. But I've decided to accept that hack since a cover is not exported by default in Skyscraper. So for the users who want to use it, they can now create a cover output node in their `artwork.xml` which will be set as thumbnail. Keep in mind that it would probably be a good idea to make sure this is not exported as a hi-res image.

**Pull request closed without merging**
