### PR TITLE
Some tiny improvements

### PR DESCRIPTION
**Pull request by vortex852456**
Oh, I prepared some commits and now I see you don't want pull requests :(

Well, now I have done the work and so I will still send this so you may have the chance to see them.
You can still decline, though :)

The main reason for my changes was the performance with screenscraper and openretro.

I've splitted my changes in seperate commits (all of them have only few code-changes). You can cherry-pick if you find some of them useful. Or you can take them as suggestion.

### Performance:
reduced the screenscraper request limit to fit allowed max 150 request/min (https://github.com/muldjord/skyscraper/commit/29ff376d78c9cbc242f3bd8fdeeac5bee55bfed9)
removed openretro threadlimit (this worked fine for me with 8 threads) (https://github.com/muldjord/skyscraper/commit/d1a17e1ba3b4ba8318035159c2733374037bdcda)
### Usability:
when screenscraper api is buisy: wait a minute before trying to continue (instead of exiting the scraping) (https://github.com/muldjord/skyscraper/commit/1bea0675b40d54afe5bb39eebb5b1fe4745c6d22 + https://github.com/muldjord/skyscraper/commit/5e42721dea247f137a9bfe94f765fc7061b60cfb)
print location of .skyscraper folder on startup (https://github.com/muldjord/skyscraper/commit/83c2bc4fc6c636d52e9125781393de470d08d181)
print full path to cache folder when scraping (https://github.com/muldjord/skyscraper/commit/f526266c385a3e5953c81592c342478a304cea79)

### Error-Handling:
added condition for errror "maximum threads per minute reached" (https://github.com/muldjord/skyscraper/commit/9216ac5c97f2a7588ec14375b61514045dbd643f)

### CODE REVIEW

**Comment by vortex852456** [comment]
Whoops, my IDE messed the format so 2 commits had "huge changes".
The complete "Files changed" is still easy to read: https://github.com/muldjord/skyscraper/pull/246/files

Btw, thanks for keeping this project alive.

**Comment by muldjord** [comment]
I always appreciate the sentiment, but yes, I don't accept PR's. But read on for explanation on why.

I would have loved to discuss these things with you prior to you spending time on it if you had asked about it on the RetroPie forums. I don't accept uninvited PR's as most users seem to miss too many obvious (correction: LESS obvious) things in how Skyscraper works.

The 1.2 sec limit is set to be a bit above 1.0 which is the limit they (the folks at ScreenScraper) have directly asked me to use to allow me to use their API. So this needs to stay. They actually blacklisted Skyscraper at one point when I had it set too low. Setting it lower than 1.0 will also cause it to draw too many requests and start giving you errors after a while. It was at 1.0 at one point and it caused problems when scraping for more than an hour.

The 1 minute pause could make sense for retries, but not implemented like this and it should *never* just keep retrying endlessly. If it fails for more than MAXRETRIES there's a good reason and it should quit. I might implement this "the Skyscraper way" which does not need extra includes. But thanks for the suggestion, it does make sense I think although the implementation is not how I would ever do it.

Lastly, any limits on threads and timers are there for a reason. The authors of the websites have asked for them in order for me to use their sites with their blessing. So these need to stay, and I would appreciate if you would also keep these in your fork. I've spend, literally, years and a lot of sweat and (almost) tears working with the good people who run the sources to get these set at defaults they will accept. So please keep them as they are.

EDIT 1: On further thought, a 1 minute pause is no good. It pauses for 1.2 seconds between the 4 retries which is how it should work. The retries are not there to try and circumvent their limits. If it doesn't work after those, it should exit since this means the user either hasn't registered or doesn't have a high enough status to scrape that often. So a 1 minute endless loop is just a way to circumvent that. See below why that is a very bad idea.

EDIT 2: I know you are just trying to be helpful. But most of your changes seem to work against all of the hours of negotiating I've had with the sources since Skyscraper was born to get the limits just right and still be allowed to use their services without being blacklisted. It's a fine balance, trust me. I don't say this lightly.

For future ideas, please just ask on the RetroPie forums. That is a lot more useful to me and can also save you some work.

**Comment by vortex852456** [comment]
I see and understand. Thanks for your detailed explanation.

Initially I thought (since the api is limited) it would be okay to handle with these limits and to not add up some extra delay. It wasn't my intention to circumvent anything :)

The loop is not endless btw, it's a for loop which respects RETRIESMAX, so after 4 minutes of failing the program would still exit. As a normal user (before I started coding) the abort was a bit annoying, had to restart the scrape and all the previous skipped entries (skipped because not found) were retried again. I guess this is worse than one request per minute, but I understand your point.
(And I now know that there is a option "--fromfile" which would have solved my problem, but I did not read the whole help in the beginning).

I would've asked you with pleasure on RetroPie forums instead of coding by myself, but I didn't know that this is your wish. Your README.md does not contain any info about contribution and the first place I saw this wish was while creating the PR (see pull_request_template.md). This is a little late imo and here on github it's the usual way to fork, fix things and open a PR (or create Issues, but I'm more the problem solver than the complainer). But don't worry, I'm not mad since I did the changes mainly to learn a bit more about c++. The faster scraping and maybe improving this nice tool for everyone was just a kind of motivation.

I will follow your wish and delete my fork (tomorrow, I don't want to get this text deleted with my fork).

**Comment by muldjord** [comment]
Thank you for understanding. You are right about the missing contribution description except for what I have in the PR text. I had not considered this and it is valuable feedback. I will add this to the README.md.

I quite dislike Github's idea of forcing PR's down our throats. The idea behind contributing to open source projects is not just code, which I'm sure you are also aware of. The feature requests and discussions leading up to code changes are, in my opinion, much, much more important than the actual code itself - at least when it comes from unknown users. And forcing those PR's on by Github creates potentially unwanted friction with the community. The fact that you mention not being mad, which I'm glad you're not, also underlines my annoyance with Github, as this is even a possible outcome. You don't owe me anything and I certainly don't own any PR anything when I haven't been made aware of it. But allowing the random PR's to even be created without a gateway to entry removes my control completely.

As someone who has often worked on other people's projects professionally it is quite clear to me how hard it is to nail a code change the first time around. Too many factors in play. A discussion with the original developer about how to best implement any feature is much more desirable. And I am not against contributions. But at that point I will have added those people to the official list of people who can work on the project or asked them to do the PR's myself.

A project on here is like a kitchen. There's a chef in there. That chef, in this case, is me. And I find the idea of some random person walking into the kitchen and suggesting recipe changes directly to the chef to be a bit absurd (that's what Github seems to think is ok). The chef has spend ages perfecting the recipe and has integral knowledge of his work. Something others can learn over a period of time. And at some point, they might get hired to work in the kitchen, which is when they might be able to do recipe changes directly.

**Comment by vortex852456** [comment]
The chef/kitchen thing is a nice metaphor :) Personally I'm more like the cook who is interested in new recipes, but I'm not a chef cook and totally understand your point ;)
I also find it kinda strange that github doesn't allow disabling PR's, in your repo this is kind of a trap.

As I see you've added some comments to your code to make the limits more clear that they are there for a good reason. Nice.

I deleted my fork.

Wish you all the best and if I'll have a request for a new or improved meal in the future, I will contact you via the forum (or issues) instead of directly sending you a reciepe ;D

**Pull request closed without merging**
